"""empty message

Revision ID: 05934f1eabd4
Revises: 
Create Date: 2022-03-01 00:43:28.196410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05934f1eabd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_detail',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('total_household', sa.Integer(), nullable=False),
    sa.Column('lowest_floor', sa.Integer(), nullable=False),
    sa.Column('highest_floor', sa.Integer(), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=False),
    sa.Column('total_dong', sa.Integer(), nullable=False),
    sa.Column('number_address', sa.String(length=100), nullable=False),
    sa.Column('road_address', sa.String(length=100), nullable=False),
    sa.Column('total_deal', sa.Integer(), nullable=False),
    sa.Column('total_jeonse', sa.Integer(), nullable=False),
    sa.Column('total_wolse', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('issue',
    sa.Column('issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('issue_pw', sa.String(length=20), nullable=False),
    sa.Column('writer', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('region',
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=False),
    sa.Column('gu', sa.String(length=10), nullable=True),
    sa.Column('dong', sa.String(length=10), nullable=True),
    sa.Column('parent_region_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('building_basic',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=50), nullable=False),
    sa.Column('building_type', sa.Enum('A1', 'B1', 'B2', name='building_code_enum'), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('household',
    sa.Column('household_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dong', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building_basic.building_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('price',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_type', sa.Enum('Deal', 'Jeonse', 'Wolse', name='sale_type_enum'), nullable=False),
    sa.Column('default_price', sa.Integer(), nullable=False),
    sa.Column('highest_price', sa.Integer(), nullable=True),
    sa.Column('wolse_price', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['household.household_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('household')
    op.drop_table('building_basic')
    op.drop_table('region')
    op.drop_table('issue')
    op.drop_table('building_detail')
    op.execute('DROP TYPE building_code_enum')
    op.execute('DROP TYPE sale_type_enum')
    # ### end Alembic commands ###
